name: mentorlink-crm
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
    build_command: pnpm install --frozen-lockfile && pnpm run build
    run_command: pnpm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_APP_URL
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_STRIPE_PREMIUM_PRICE_ID
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_STRIPE_PRO_PRICE_ID
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_STRIPE_ENTERPRISE_PRICE_ID
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_STRIPE_YEARLY_PREMIUM_PRICE_ID
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_STRIPE_YEARLY_PRO_PRICE_ID
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_STRIPE_YEARLY_ENTERPRISE_PRICE_ID
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_STRIPE_TRIAL_DAYS
        scope: RUN_TIME
        type: SECRET 