import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/hooks/useAuth"; // Import AuthProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CRM Pipeline", // Updated title
  description: "Deal Pipeline CRM generated by Manus AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', marginTop: '24px', marginBottom: '16px' }}>
            <img src="/logo.png" alt="MentorLink Logo" style={{ width: '200px', height: '200px', objectFit: 'contain' }} />
          </div>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}

